'use client';

/**
 * "Actions assigned to you" — the receiving side of cross-agent task assignment.
 *
 * Shows action_items whose assigned_to_role_type matches the current role.
 * Each item can have its status advanced (PATCH /api/actions) and a draft
 * response generated by a specialist agent ("Draft my response", which calls
 * /api/agent with the action's context pre-seeded). The draft is editable; on
 * "Accept & save" it is persisted on the action (PATCH with response_md) and
 * becomes visible to the raiser in their "Responses to actions you raised"
 * panel. New assignments + responses arrive live via Supabase Realtime on the
 * action_items table (migrations 0009 / 0010).
 */

import { useCallback, useEffect, useState } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { createSupabaseBrowserClient } from '@/lib/supabase-browser';
import { stripActionsBlock } from '@/lib/action-parser';

interface ActionItem {
  id: string;
  project_id: string | null;
  source_ref: string | null;
  description: string;
  assigned_to_role_type: string;
  raised_by_role_type: string | null;
  raised_by_agent_type: string | null;
  status: string;
  urgency: string;
  assignment_flagged: boolean;
  response_md: string | null;
  responded_by_role_type: string | null;
  responded_at: string | null;
  created_at: string;
}

const ROLE_LABELS: Record<string, string> = {
  pm: 'Senior PM',
  procurement: 'Procurement Strategist',
  risk: 'Risk Analyst',
  sponsor: 'VP Sponsor',
  commercial: 'Commercial Manager',
  project_controls: 'Project Controls',
  program_manager: 'Program Manager',
  engineering_manager: 'Engineering Manager',
  construction_manager: 'Construction Manager',
  hse_manager: 'HSE Manager',
};

function roleLabel(rt: string | null): string {
  if (!rt) return 'a colleague';
  return ROLE_LABELS[rt] ?? rt;
}

// Strip markdown emphasis/headers so the editable draft reads as clean prose
// in the plain <textarea> (no literal ** or # showing). Bullets stay as "- ".
function toPlainProse(md: string): string {
  return md
    .replace(/\*\*(.*?)\*\*/g, '$1')   // **bold** -> bold
    .replace(/__(.*?)__/g, '$1')        // __bold__ -> bold
    .replace(/(^|\n)\s{0,3}#{1,6}\s*/g, '$1') // strip ATX headers
    .replace(/(^|\n)\s{0,3}\*\s+/g, '$1- ')  // '* ' bullets -> '- '
    .trim();
}

const STATUSES = ['Open', 'Acknowledged', 'In progress', 'Done'];

function urgencyClass(u: string): string {
  if (u === 'H') return 'bg-red-100 text-red-800';
  if (u === 'L') return 'bg-gray-100 text-gray-700';
  return 'bg-amber-100 text-amber-800';
}

interface DraftState {
  loading?: boolean;
  text?: string;     // editable draft text (present once drafted, before save)
  error?: string;
  saving?: boolean;
}

export function ActionQueue({ token, roleType }: { token: string; roleType: string }) {
  const [items, setItems] = useState<ActionItem[] | null>(null);
  const [newIds, setNewIds] = useState<Set<string>>(new Set());
  const [drafts, setDrafts] = useState<Record<string, DraftState>>({});

  const load = useCallback(async () => {
    try {
      const res = await fetch(`/api/actions?scope=mine&token=${encodeURIComponent(token)}`, {
        cache: 'no-store',
      });
      const data = await res.json();
      setItems((data.items ?? []) as ActionItem[]);
    } catch {
      setItems([]);
    }
  }, [token]);

  useEffect(() => {
    load();
  }, [load]);

  // Realtime: new/updated assignments for this role appear without a refresh.
  useEffect(() => {
    const supabase = createSupabaseBrowserClient();
    const channel = supabase
      .channel('action_items_for_role')
      .on(
        'postgres_changes',
        { event: 'INSERT', schema: 'public', table: 'action_items' },
        (payload) => {
          const row = payload.new as ActionItem;
          if (row.assigned_to_role_type !== roleType) return;
          setItems((prev) => {
            const list = prev ?? [];
            if (list.some((a) => a.id === row.id)) return list;
            return [row, ...list];
          });
          setNewIds((prev) => new Set(prev).add(row.id));
          setTimeout(() => {
            setNewIds((prev) => {
              const next = new Set(prev);
              next.delete(row.id);
              return next;
            });
          }, 4000);
        },
      )
      .on(
        'postgres_changes',
        { event: 'UPDATE', schema: 'public', table: 'action_items' },
        (payload) => {
          const row = payload.new as ActionItem;
          if (row.assigned_to_role_type !== roleType) return;
          setItems((prev) => (prev ?? []).map((a) => (a.id === row.id ? row : a)));
        },
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, [roleType]);

  async function updateStatus(id: string, status: string) {
    setItems((prev) => (prev ?? []).map((a) => (a.id === id ? { ...a, status } : a)));
    try {
      await fetch('/api/actions', {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ token, id, status }),
      });
    } catch {
      // Realtime UPDATE will reconcile if this failed.
    }
  }

  async function draftResponse(item: ActionItem) {
    setDrafts((prev) => ({ ...prev, [item.id]: { loading: true } }));
    const refClause = item.source_ref ? ` arising from risk ${item.source_ref}` : '';
    const prompt =
      `You have been assigned this action${refClause} as the ${roleLabel(roleType)}: ` +
      `"${item.description}". Draft your response as the owning role — the concrete steps you will ` +
      `take to deliver it, anything you need from other roles, and a target timeframe. ` +
      `Keep it to 4-6 sentences, written as the responsible owner.`;
    try {
      const res = await fetch('/api/agent', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ token, agent_type: 'auto', user_prompt: prompt, concise: true }),
      });
      const data = await res.json();
      if (!res.ok) {
        setDrafts((prev) => ({ ...prev, [item.id]: { error: data.error ?? `HTTP ${res.status}` } }));
      } else {
        setDrafts((prev) => ({ ...prev, [item.id]: { text: toPlainProse(stripActionsBlock(data.output_md ?? '')) } }));
        if (item.status === 'Open') updateStatus(item.id, 'Acknowledged');
      }
    } catch (err) {
      setDrafts((prev) => ({ ...prev, [item.id]: { error: (err as Error).message } }));
    }
  }

  function editDraft(id: string, text: string) {
    setDrafts((prev) => ({ ...prev, [id]: { ...prev[id], text } }));
  }

  function discardDraft(id: string) {
    setDrafts((prev) => {
      const next = { ...prev };
      delete next[id];
      return next;
    });
  }

  async function acceptResponse(item: ActionItem) {
    const text = drafts[item.id]?.text?.trim();
    if (!text) return;
    setDrafts((prev) => ({ ...prev, [item.id]: { ...prev[item.id], saving: true } }));
    try {
      const res = await fetch('/api/actions', {
        method: 'PATCH',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ token, id: item.id, response_md: text }),
      });
      const data = await res.json();
      if (!res.ok || !data.item) {
        setDrafts((prev) => ({ ...prev, [item.id]: { ...prev[item.id], saving: false, error: data.error ?? 'Save failed' } }));
        return;
      }
      // Persisted — reflect the saved row and clear the editing draft.
      setItems((prev) => (prev ?? []).map((a) => (a.id === item.id ? (data.item as ActionItem) : a)));
      discardDraft(item.id);
    } catch (err) {
      setDrafts((prev) => ({ ...prev, [item.id]: { ...prev[item.id], saving: false, error: (err as Error).message } }));
    }
  }

  if (items === null || items.length === 0) return null;

  const openCount = items.filter((a) => a.status !== 'Done').length;

  return (
    <section className="mb-8 rounded-lg border bg-card p-5">
      <div className="flex items-center justify-between gap-3">
        <h2 className="text-sm font-semibold uppercase tracking-wider text-muted-foreground">
          Actions assigned to you
        </h2>
        <span className="rounded-full bg-muted px-2.5 py-0.5 text-xs font-medium">
          {openCount} open · {items.length} total
        </span>
      </div>

      <ul className="mt-4 space-y-3">
        {items.map((a) => {
          const draft = drafts[a.id];
          const isNew = newIds.has(a.id);
          const hasSavedResponse = !!a.response_md && !draft;
          return (
            <li
              key={a.id}
              className={`rounded-md border bg-background p-3.5 transition ${
                isNew ? 'ring-2 ring-foreground/30' : ''
              }`}
            >
              <div className="flex items-start justify-between gap-3">
                <div className="min-w-0">
                  <p className="text-sm">{a.description}</p>
                  <p className="mt-1 flex flex-wrap items-center gap-2 text-[11px] text-muted-foreground">
                    <span>raised by {roleLabel(a.raised_by_role_type)}</span>
                    {a.source_ref && <span className="font-mono">{a.source_ref}</span>}
                    <span className={`rounded-full px-2 py-0.5 font-medium ${urgencyClass(a.urgency)}`}>
                      {a.urgency === 'H' ? 'High' : a.urgency === 'L' ? 'Low' : 'Med'} urgency
                    </span>
                    {a.assignment_flagged && (
                      <span className="rounded-full bg-amber-100 px-2 py-0.5 font-medium text-amber-800">
                        auto-routed to PM — confirm owner
                      </span>
                    )}
                  </p>
                </div>
                <div className="flex shrink-0 items-center gap-2">
                  <select
                    value={a.status}
                    onChange={(e) => updateStatus(a.id, e.target.value)}
                    className="rounded-md border bg-background px-2 py-1 text-xs"
                  >
                    {STATUSES.map((s) => (
                      <option key={s} value={s}>
                        {s}
                      </option>
                    ))}
                  </select>
                </div>
              </div>

              {/* Saved response — visible once accepted (and to the raiser elsewhere). */}
              {hasSavedResponse && (
                <div className="mt-3 rounded-md border border-emerald-200 bg-emerald-50/60 p-3">
                  <p className="mb-1 flex items-center gap-2 text-[10px] font-medium uppercase tracking-wider text-emerald-700">
                    ✓ Response saved
                    <span className="font-normal normal-case tracking-normal text-emerald-700/80">
                      sent to {roleLabel(a.raised_by_role_type)}
                    </span>
                  </p>
                  <article className="prose prose-sm max-w-none dark:prose-invert">
                    <ReactMarkdown remarkPlugins={[remarkGfm]}>{a.response_md as string}</ReactMarkdown>
                  </article>
                  <button
                    type="button"
                    onClick={() => draftResponse(a)}
                    className="mt-2 rounded-md border bg-background px-2.5 py-1 text-[11px] font-medium transition hover:bg-muted"
                  >
                    Draft again
                  </button>
                </div>
              )}

              {/* Draft action button (when nothing drafted/saved yet). */}
              {!draft && !hasSavedResponse && (
                <div className="mt-3">
                  <button
                    type="button"
                    onClick={() => draftResponse(a)}
                    className="rounded-md bg-foreground px-3 py-1.5 text-xs font-medium text-background transition hover:opacity-90"
                  >
                    Draft my response
                  </button>
                </div>
              )}

              {/* Drafting in progress / editable draft. */}
              {draft && (
                <div className="mt-3 rounded-md border bg-muted/20 p-3">
                  {draft.loading ? (
                    <p className="text-xs text-muted-foreground">
                      <span className="inline-block animate-pulse">●</span> Drafting your response…
                    </p>
                  ) : (
                    <>
                      <p className="mb-1.5 text-[10px] font-medium uppercase tracking-wider text-muted-foreground">
                        Drafted response — review & edit, then accept
                      </p>
                      <textarea
                        value={draft.text ?? ''}
                        onChange={(e) => editDraft(a.id, e.target.value)}
                        rows={7}
                        className="w-full resize-y rounded-md border bg-background px-2.5 py-2 text-sm focus:outline-none focus:ring-1 focus:ring-foreground/30"
                      />
                      <div className="mt-2 flex items-center gap-2">
                        <button
                          type="button"
                          disabled={draft.saving || !draft.text?.trim()}
                          onClick={() => acceptResponse(a)}
                          className="rounded-md bg-emerald-600 px-3 py-1.5 text-xs font-medium text-white transition hover:opacity-90 disabled:opacity-50"
                        >
                          {draft.saving ? 'Saving…' : 'Accept & save'}
                        </button>
                        <button
                          type="button"
                          disabled={draft.saving}
                          onClick={() => discardDraft(a.id)}
                          className="rounded-md border bg-background px-3 py-1.5 text-xs font-medium transition hover:bg-muted disabled:opacity-50"
                        >
                          Discard
                        </button>
                        <button
                          type="button"
                          disabled={draft.saving}
                          onClick={() => draftResponse(a)}
                          className="rounded-md border bg-background px-3 py-1.5 text-xs font-medium transition hover:bg-muted disabled:opacity-50"
                        >
                          Redraft
                        </button>
                      </div>
                    </>
                  )}
                  {draft.error && <p className="mt-2 text-xs text-red-600">{draft.error}</p>}
                </div>
              )}
            </li>
          );
        })}
      </ul>
    </section>
  );
}
